name = "ParametrizedSurfaces"
uuid = "b48152b0-a081-4a9a-b393-d67edc514fc9"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
